// 정적 데이터(예시·파트·체크리스트) — legacy.jsx에서 분리(유지보수용). 동작 변경 없음.
export const SELF_INTRO_EXAMPLES = {
  Q1: '예: 1) CAD 기구 설계  2) 공차 분석·검토  3) 시제품 제작·검증 — 공고에서 3회 이상 반복된 단어',
  Q2: "예: '공차 분석'은 단순 수치 계산이 아니라 \"왜 조립 단계에서 불량이 나는가\"를 치수로 규명해 다음 설계를 정하는 일입니다.",
  Q3: '예: 잘하는 사람은 도면에서 \'다음 설계 개선\'을 끌어내고, 못하는 사람은 측정 보고서로 끝냅니다.',
  Q4: '예: 2024년 하반기 자동차 부품사 기구설계팀에서 6개월간 인턴을 했습니다. 한 브래킷 조립 시제품 불량률이 18%로 높아 양산 일정이 밀리고 있었는데, 제가 SolidWorks로 조립 공차를 누적·분석해 간섭 위험 부위를 3곳으로 좁히고 해당 부위만 끼워맞춤 공차를 재설계해 시제품으로 검증했습니다. (구체적인 장면·기간·내가 한 일이 드러나야 채용담당자가 "진짜 해봤구나"를 느낍니다)',
  'Q5-a': '예: 인턴 시작 전에는 설계를 "감각 있는 형상과 깔끔한 도면"의 일이라고 생각했고, 공차는 마지막에 채워 넣는 보조 작업이라고만 여겼습니다.',
  'Q5-b': '예: 그런데 똑같은 형상이라도 "어느 부위에 공차를 얼마나 주는가"에 따라 조립 불량률이 30%p나 갈리는 것을 시제품으로 직접 확인한 순간, 형상보다 공차 설계가 먼저라는 걸 몸으로 깨달았습니다. (깨달음의 "순간"이 구체적일수록 진정성이 보입니다)',
  'Q5-c': '예: 그 이후로는 어떤 설계든 "기능 정의 → 공차 가설 → 시제품 → 검증" 순서로 접근하는 게 습관이 됐고, 공모전·캡스톤 프로젝트에서도 먼저 치수로 문제를 정의한 뒤 움직였습니다. (이 변화가 앞으로 일할 때도 이어진다는 신호)',
  Q6: '예: 조립 공차 재설계로 시제품 불량률 18%→13%(30% 감소), 양산 일정 2주 단축, 그리고 이 검토 방식을 팀 공차 체크리스트로 표준화해 다른 설계자도 계속 쓰게 만들었습니다. (확실한 수치만; 수치가 없으면 "재발방지를 표준화해 같은 실수가 사라졌다"처럼 변화 중심으로)',
  Q7: '예: 제 장점은 "도면에서 멈추지 않고 시제품 검증까지 끌어내는 실행력"입니다. ("성실함·책임감" 같은 누구나 쓰는 표현 대신, 내 경험으로 증명되는 한 단어로)',
  Q8: '예: [초기 모습] 도면을 깔끔히 그리는 정도였지만 → [경험] 인턴에서 공차 분석을 멈추지 않고 직접 시제품 검증으로 연결하면서 → [직무 역량] 가설을 시제품으로 검증해 설계를 바꾸는 공차 설계력으로 발전했습니다.',
  Q9: '예: 귀사는 외주가 아닌 자체 시작품 라인과 측정 설비를 보유해 설계부터 양산 검증까지 끝까지 다룰 수 있고, 신입에게도 부품 설계를 맡긴다는 점이 다른 회사와 결정적으로 다릅니다. "데이터로 설계를 바꾸고 싶다"는 제 방향이 가장 빨리 실현될 곳이라 지원했습니다. (회사명만 빼면 다른 곳에도 쓸 수 있는 문장이면 다시 쓰세요)',
  Q10: '예: 입사 직후에는 인턴 때 다룬 SolidWorks·공차 분석 역량으로 귀사 신규 부품의 조립 공차를 검토·개선하는 업무에 바로 기여하겠습니다. 아직 부족한 FEA 구조해석은 입사 후 사내 해석 케이스로 매일 모델을 돌려 3개월 안에 끌어올려, 해석 담당자에게 의존하지 않고 설계 단계에서 강성·발열 위험을 직접 잡는 데까지 기여 범위를 넓히겠습니다. (① 직무 업무와 연결 ② 지금 역량으로 할 수 있는 일 ③ 부족한 역량을 어떻게 채우며 기여를 넓힐지)',
  Q11: '예: 자작자동차 동아리·인턴에서 CAD로 부품을 설계하고 공차를 검증한 경험을 쌓아, 이 직무에서 시제품 품질을 끌어올리는 데 기여할 수 있는 김지원입니다. (강점 선언보다 "쌓은 경험 → 직무 기여"로)',
  Q12: '예: CAD 기구 설계 · 공차 재설계로 불량률 30%↓ · 시제품 검증 실행력 · 자작자동차 설계',
  Q13: '예: (30초 키워드) + 누적 공차 분석 · 양산 일정 2주 단축 · 방열 구조 고도화 기여',
  Q14: '예: …지향하는 김지원입니다. 자동차 부품사 기구설계 인턴에서 조립 불량 부위를 누적 공차로 정의했습니다.',
  Q15: '예: \'어느 부위에 얼마나\'가 핵심임을 깨닫고 끼워맞춤 공차를 재설계해 시제품 불량률을 30% 낮췄습니다.',
  Q16: '예: 이 경험으로 도면에서 시제품 검증까지 끌어내는 실행력을 갖췄습니다.',
  Q17: '예: 이 실행력을 자체 시작품 라인을 갖춘 귀사에서 부품 공차 개선으로 발휘하고 싶습니다.',
  Q18: '예(30초): 안녕하세요. 자동차 부품사 기구설계 인턴에서 조립 불량 부위를 누적 공차로 정의하고 끼워맞춤 공차를 재설계한 경험으로, 이 직무에서 시제품 품질을 끌어올리는 데 기여할 수 있는 김지원입니다. 실제로 시제품 불량률을 30% 낮췄고, 자체 시작품 라인으로 설계를 직접 검증할 수 있는 귀사에서 바로 기여하겠습니다.',
  Q19: '예(1분): 안녕하세요. 자동차 부품사 기구설계 인턴에서 조립 불량 부위를 누적 공차로 정의하고 끼워맞춤 공차를 재설계한 경험으로, 이 직무에서 시제품 품질을 끌어올리는 데 기여할 수 있는 김지원입니다. 실제로 시제품 불량률 30% 감소, 양산 일정 2주 단축을 만들었고, 형상보다 \'어느 부위에 공차를 얼마나 주는가\'가 품질을 가른다는 것을 시제품으로 확인하며 감이 아닌 가설·검증으로 일하는 법을 익혔습니다. 입사 후에는 부품의 조립 공차를 분석해 방열 구조와 신규 부품의 공차를 시제품으로 최적화하고, 3년 안에 모듈 단위 공차 설계를 오너십 있게 책임지는 설계자로 성장하겠습니다.',
  Q20: '예: 소리 내어 읽고 군더더기(\'저는\', \'열심히\')를 빼고 숫자·고유명사를 남기세요. \'열심히 하겠습니다\' → \'조립 공차를 직접 재설계하겠습니다\'.',
};

export const SELF_INTRO_EXAMPLES_CAREER = {
  Q1: '예: 1) 전력 회로 설계  2) DC-DC 컨버터 효율 개선  3) 신뢰성 검증 — 공고에서 3회 이상 반복된 단어',
  Q2: "예: '효율 개선'은 단순 부품 교체가 아니라 \"어느 손실에서 전력이 새는가\"를 측정으로 규명해 회로 토폴로지를 바꾸는 일입니다.",
  Q3: '예: 잘하는 사람은 측정 파형에서 \'다음 설계 개선\'을 끌어내고, 못하는 사람은 시험 성적서로 끝냅니다.',
  Q4: '예: 5년차 전자 HW 엔지니어로 전력 회로를 설계해왔습니다. 양산 중인 DC-DC 컨버터의 변환 효율이 87%에 머물러 발열·수명 이슈가 있었는데, 손실 분석으로 스위칭 손실이 주 원인임을 규명하고 토폴로지·소자를 재설계해 효율을 92%로 끌어올려 시제품으로 검증했습니다. (구체적 장면·기간·내가 한 일이 드러나야 "진짜 해봤구나"를 느낍니다)',
  'Q5-a': '예: 입사 초에는 회로 설계를 "스펙대로 부품을 배치하고 동작시키는 일"이라 생각했고, 효율·발열은 사후에 방열로 잡으면 된다고 여겼습니다.',
  'Q5-b': '예: 그런데 같은 회로라도 "어느 손실을 먼저 줄이느냐"에 따라 효율이 5%p 이상 갈리는 것을 측정으로 직접 확인한 순간, 방열보다 손실 설계가 먼저라는 걸 깨달았습니다.',
  'Q5-c': '예: 그 이후로는 어떤 설계든 "손실 분해 → 가설 → 시제품 측정 → 검증" 순서로 접근하는 게 습관이 됐습니다.',
  Q6: '예: DC-DC 컨버터 재설계로 변환 효율 87%→92%(5%p↑), 발열 10℃ 저감, 그리고 이 손실 분석 절차를 팀 설계 리뷰 체크리스트로 표준화했습니다.',
  Q7: '예: 제 장점은 "측정에서 멈추지 않고 회로 재설계까지 끌어내는 실행력"입니다.',
  Q8: '예: [초기 모습] 스펙대로 회로를 동작시키는 정도였지만 → [경험] 손실 분석을 직접 재설계로 연결하면서 → [직무 역량] 측정 데이터로 토폴로지를 바꾸는 전력 설계력으로 발전했습니다.',
  Q9: '예: 귀사는 전원 모듈을 내재화해 설계부터 신뢰성 검증까지 직접 다루고, 경력자에게 회로 오너십을 맡긴다는 점이 다릅니다. "측정으로 회로를 바꾸고 싶다"는 제 방향이 가장 빨리 실현될 곳이라 지원했습니다.',
  Q10: '예: 입사 직후에는 5년간 다룬 전력 회로·손실 분석 역량으로 귀사 전원 모듈의 효율·발열을 개선하는 업무에 바로 기여하겠습니다. 아직 부족한 EMC 대응은 입사 후 사내 시험 케이스로 보완해 3개월 안에 끌어올리겠습니다. (① 직무 업무와 연결 ② 지금 역량 ③ 부족 역량 보완)',
  Q11: '예: 전력 회로를 5년간 설계하며 효율을 끌어올려온 경험으로, 이 직무의 전원 효율 개선에 기여할 수 있는 5년차 김경력입니다. (강점 선언보다 "쌓은 경험 → 직무 기여"로)',
  Q12: '예: 전력 회로 설계 · DC-DC 효율 5%p↑ · 발열 10℃↓ · 손실 분석 실행력',
  Q13: '예: (30초 키워드) + 신뢰성 검증 · 설계 리뷰 표준화 · 전원 모듈 기여',
  Q14: '예: …5년차 김경력입니다. 양산 DC-DC 컨버터의 손실을 측정으로 분해했습니다.',
  Q15: '예: \'어느 손실을 먼저\'가 핵심임을 깨닫고 토폴로지를 재설계해 효율을 5%p 높였습니다.',
  Q16: '예: 이 경험으로 측정에서 회로 재설계까지 끌어내는 실행력을 갖췄습니다.',
  Q17: '예: 이 실행력을 전원 모듈을 내재화한 귀사에서 효율 개선으로 발휘하고 싶습니다.',
  Q18: '예(30초): 안녕하세요. 전력 회로를 5년간 설계하며 DC-DC 컨버터 손실을 분석·재설계한 경험으로, 이 직무의 전원 효율 개선에 기여할 수 있는 5년차 김경력입니다. 실제로 변환 효율을 5%p 높이고 발열을 10℃ 낮췄으며, 전원 모듈을 내재화한 귀사에서 바로 기여하겠습니다.',
  Q19: '예(1분): 안녕하세요. 전력 회로를 5년간 설계하며 DC-DC 컨버터의 손실을 측정으로 분해하고 토폴로지를 재설계한 경험으로, 이 직무의 전원 효율 개선에 기여할 수 있는 5년차 김경력입니다. 실제로 변환 효율 87%→92%(5%p↑), 발열 10℃ 저감을 만들었고, 방열보다 손실 설계가 먼저라는 것을 측정으로 확인하며 감이 아닌 가설·검증으로 일하는 법을 익혔습니다. 입사 후에는 전원 모듈의 효율·발열을 개선하고, 3년 안에 전원 설계를 오너십 있게 책임지는 엔지니어로 성장하겠습니다.',
  Q20: '예: 소리 내어 읽고 군더더기(\'저는\', \'열심히\')를 빼고 숫자·고유명사를 남기세요. \'열심히 하겠습니다\' → \'전력 회로를 직접 재설계하겠습니다\'.',
};

export const PARTS = [
  {
    part: 1,
    title: "직무 분석 — 직무 이해도를 보여준다",
    intro: '',
    stuckNote: "Q1~Q2에 답이 안 된다면 → 채용공고를 아직 충분히 분석하지 못한 것입니다 → 채용공고 분석 가이드를 먼저 진행하세요 Q3에 답이 안 된다면 → 직무에 대한 리서치가 부족한 것입니다 → 직무분석 가이드를 먼저 진행하거나, 같은 직무 채용공고 3개 이상을 비교해보세요 혹은 Q2에서 해석한 키워드 중 가장 중요하다고 생각하는 것 1개를 골라 Q3 대신 사용해도 됩니다",
    questions: [
      { label: "Q1", question: "채용공고 직무상세에서 반복되거나 눈에 띄는 키워드 3개를 적으세요", tip: '', checkpoint: "채용담당자: \"직무상세내용을 제대로 읽었는가?\"", placeholder: "1. 2. 3.", referenceQuestions: [], relatedWorkbooks: ['job_analysis', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
      { label: "Q2", question: "각 키워드가 실제 업무에서 무엇을 의미하는지 본인의 말로 해석하세요", tip: "직무상세내용 베껸쓰기 금지. '이 역량이 왜 중요한지'까지", checkpoint: "채용담당자: \"직무의 본질을 이해하고 있는가?\"", placeholder: '', referenceQuestions: [], relatedWorkbooks: ['job_analysis', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
      { label: "Q3", question: "이 직무에서 잘하는 사람과 못하는 사람의 결정적 차이는 무엇이라고 생각하나요?", tip: "이것이 첫 문장의 핵심 키워드 원천", checkpoint: "채용담당자: \"직무 이해의 깊이가 있는가?\"", placeholder: '', referenceQuestions: ["Q1", "Q2"], relatedWorkbooks: ['job_analysis', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
    ],
  },
  {
    part: 2,
    title: "경험 연결 — 즉시 전력화 가능성을 보여준다",
    intro: '',
    stuckNote: "Q4에 답이 안 된다면 → 경험 정리가 안 된 것입니다 → 경험정리 가이드워크북으로 경험을 먼저 정리하세요 Q5-a~c에 답이 안 된다면 → 경험의 의미를 아직 정리하지 못한 것입니다 → Q4에 적은 경험을 다시 떠올리며 '이 경험 전과 후에 나는 어떻게 달라졌나?'를 자문해보세요 Q6에 답이 안 된다면 → 성과가 없어도 괜찮습니다. Q5-b와 Q5-c의 깨달음이 성과를 대체합니다",
    questions: [
      { label: "Q4", question: "직무 키워드와 연결되는 나의 경험은? (1~2개)", tip: "없으면 유사 경험으로 대체. 수업과제, 동아리, 아르바이트에서 무언가를 분석/기획/관리/조율해본 경험이 있나요?", checkpoint: "채용담당자: \"실제로 해봤구나\"", placeholder: '', referenceQuestions: [], relatedWorkbooks: ['experience', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
      { label: "Q5-a", question: "이 경험을 하기 전에는 이 직무(또는 이 역량)에 대해 어떻게 생각했나요?", tip: "변화 '전' 상태를 먼저 잡습니다", checkpoint: "깨달음 도출 1/3단계", placeholder: '', referenceQuestions: ["Q4"], relatedWorkbooks: ['experience', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
      { label: "Q5-b", question: "경험을 하면서 그 생각이 어떻게 바뀌었나요? 구체적으로 어떤 순간에 바뀌었나요?", tip: "'이때 처음으로 ~를 느꼈습니다' 형식", checkpoint: "깨달음 도출 2/3단계", placeholder: '', referenceQuestions: ["Q4", "Q5-a"], relatedWorkbooks: ['experience', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
      { label: "Q5-c", question: "그 변화가 이후에 어떤 영향을 줬나요? 이전과 다르게 행동하거나 생각하게 된 것이 있나요?", tip: "Q5-b + Q5-c를 합치면 자기소개의 '깨달음' 문장이 됩니다", checkpoint: "깨달음 도출 3/3단계", placeholder: '', referenceQuestions: ["Q4", "Q5-b"], relatedWorkbooks: ['self_introduction', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
      { label: "Q6", question: "구체적 성과가 있나요? (확실한 것만. 없으면 의미 중심으로)", tip: "과장은 꼬리질문에서 바로 들통납니다", checkpoint: "채용담당자: \"결과를 내는 사람인가\"", placeholder: '', referenceQuestions: ["Q4", "Q5-b", "Q5-c"], relatedWorkbooks: ['interview_new', 'interview_career', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
    ],
  },
  {
    part: 3,
    title: "강점 도출 — 함께 일하고 싶은 동료인가를 보여준다",
    intro: '',
    stuckNote: "Q7~Q8에 답이 안 된다면 → 성격의 장단점 정리가 안 된 것입니다 → 성격의 장단점 작성 가이드를 먼저 진행하세요 또는 가족/친구에게 '내 장점이 뭐야?'라고 직접 물어보세요. 의외의 답이 나옵니다",
    questions: [
      { label: "Q7", question: "나의 장점은? ('성실함' 같은 범용 표현 금지)", tip: "다른 사람들이 나에게 자주 하는 칭찬은? 팀에서 자연스럽게 맡게 되는 역할은?", checkpoint: "채용담당자: \"그 장점이 직무에서 어떻게 쓰이는데?\"", placeholder: '', referenceQuestions: [], relatedWorkbooks: ['job_analysis', 'experience', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
      { label: "Q8", question: "그 장점이 경험을 통해 어떻게 '직무에서 활용 가능한 역량'으로 발전했나요? (공식: [초기 장점] → [경험을 통해] → [직무 역량으로])", tip: '', checkpoint: "채용담당자: \"이 사람과 함께 일하면 이런 가치가 있겠다\"", placeholder: '', referenceQuestions: ["Q4", "Q7"], relatedWorkbooks: ['experience', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
    ],
  },
  {
    part: 4,
    title: "마무리 — 오래 함께할 수 있는 사람인가를 보여준다",
    intro: '',
    stuckNote: "Q9에 답이 안 된다면 → 회사 리서치가 부족한 것입니다 → 채용공고 분석 가이드의 기업 분석 파트를 먼저 진행하세요 Q10에 답이 안 된다면 → 직무 이해가 부족한 것입니다 → PART 1으로 돌아가 Q1~Q2를 다시 확인하세요",
    questions: [
      { label: "Q9", question: "이 회사에 지원한 구체적 이유는? (다른 회사에도 쓸 수 있는 말이면 다시 쓰세요)", tip: "회사의 구체적 특징과 나의 연결점", checkpoint: "채용담당자: \"진짜 우리 회사를 알고 온 건가\"", placeholder: '', referenceQuestions: [], relatedWorkbooks: ['experience', 'self_introduction', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
      { label: "Q10", question: "입사 후 구체적으로 어떤 역량으로 어떤 업무에 기여하고 싶나요?", tip: "'열심히 하겠습니다' 금지. [역량]+[업무] 형식으로", checkpoint: "채용담당자: \"이 사람을 뽑으면 이 업무를 맡길 수 있겠다\"", placeholder: '', referenceQuestions: ["Q1", "Q2", "Q3", "Q8"], relatedWorkbooks: ['experience', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
    ],
  },
  {
    part: 5,
    title: "자기소개 조립 — 키워드 카드 만들기",
    intro: '',
    stuckNote: "Q11에 답이 안 된다면 → PART 1의 Q3이 부실한 것입니다. Q3 또는 Q2에서 핵심 키워드를 다시 확인하세요 Q12~Q13에 답이 안 된다면 → PART 2~4의 답변이 부실한 것입니다. 해당 PART로 돌아가 보완하세요",
    questions: [
      { label: "Q11", question: "첫 문장을 만드세요: [직무 관련 경험으로 쌓은 핵심 역량] + [이 직무에 할 수 있는 기여] + [이름]", tip: "Q3의 '결정적 차이'와 직무상세내용 업무 목록을 결합", checkpoint: "채용담당자: \"직무를 알고 강점도 있구나\"", placeholder: '', referenceQuestions: ["Q3", "Q7", "Q8"], relatedWorkbooks: ['job_analysis', 'experience', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
      { label: "Q12", question: "30초 버전 키워드 카드 (4~5개) 첫문장 + 핵심경험의미 + 강점발전 + 지원동기", tip: "이 키워드만 보고 30초간 말할 수 있어야 합니다", checkpoint: '', placeholder: "① ② ③ ④", referenceQuestions: ["Q11", "Q4", "Q5-c", "Q8", "Q10"], relatedWorkbooks: ['experience', 'self_introduction', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
      { label: "Q13", question: "1분 버전 키워드 카드 (8~10개) 30초 + 성과/차별점 + 구체적 기여방향 추가", tip: "면접 당일 출력해서 직전에 확인할 나침반", checkpoint: '', placeholder: "① ② ③ ④ ⑤ ⑥ ⑦ ⑧", referenceQuestions: ["Q12", "Q6"], relatedWorkbooks: ['self_introduction', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
    ],
  },
  {
    part: 6,
    title: "연결 — 키워드 사이를 자연스럽게 잇기",
    intro: "키워드만 있으면 '나열'이 됩니다. 키워드 사이를 자연스럽게 잇는 연결 문장이 있어야 '이야기'가 됩니다. 아래 4개의 연결 지점을 채우세요.",
    stuckNote: '',
    questions: [
      { label: "Q14", question: "첫 문장(Q11) → 경험(Q4)", tip: '', checkpoint: "Bad: '저는 대학 시절 프로젝트를 했습니다' (갑작스러운 전환) Good: '이런 가치를 깨달은 계기는 OO 프로젝트에서였습니다' (첫 문장의 가치와 연결)", placeholder: '', referenceQuestions: ["Q11", "Q4"], relatedWorkbooks: ['career_roadmap', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
      { label: "Q15", question: "깨달음(Q5) → 성과(Q6)", tip: '', checkpoint: "Bad: '그리고 공차 분석도 해봤습니다' (나열) Good: '이 깨달음을 바탕으로 실제로 적용해본 경험이 있습니다' (인과관계)", placeholder: '', referenceQuestions: ["Q5-a", "Q5-b", "Q5-c", "Q6"], relatedWorkbooks: ['experience', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
      { label: "Q16", question: "성과(Q6) → 강점(Q8)", tip: '', checkpoint: "Bad: '저의 장점은 꼼꼼함입니다' (맥락 없는 전환) Good: '이런 경험들을 통해 꼼꼼함이 디테일에서 개선점을 찾는 분석력으로 발전했습니다' (경험에서 강점으로)", placeholder: '', referenceQuestions: ["Q6", "Q8"], relatedWorkbooks: ['experience', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
      { label: "Q17", question: "강점(Q8) → 지원동기(Q9~10)", tip: '', checkpoint: "Bad: '귀사에 입사하고 싶습니다' (동기 없음) Good: '이 공차 설계력을 귀사의 자체 시작품 라인 환경에서 발휘하고 싶습니다' (강점이 회사 업무로 직접 연결)", placeholder: '', referenceQuestions: ["Q8", "Q9", "Q10"], relatedWorkbooks: ['experience', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
    ],
  },
  {
    part: 7,
    title: "초안 작성 — 키워드를 보고 말한 후, 그대로 적기",
    intro: "문장을 '쓰고 외우는' 것이 아니라, '말하고 받아 적는' 것입니다. 입으로 먼저 말해야 자연스럽고, 적은 것을 다듬어야 완성도가 올라갑니다.",
    stuckNote: '',
    questions: [
      { label: "Q18", question: "30초 버전 초안", tip: "Q12의 키워드 카드(4~5개)만 보고, 소리 내어 30초간 말합니다. 그리고 말한 내용을 그대로 적으세요. 문장을 다듬지 마세요.", checkpoint: '', placeholder: "[30초 버전] 키워드만 보고 말한 후, 그대로 받아 적으세요", referenceQuestions: ["Q12"], relatedWorkbooks: ['self_introduction', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
      { label: "Q19", question: "1분 버전 초안", tip: "Q13의 키워드 카드(8~10개) + Q14~Q17의 연결 문장을 함께 보고, 소리 내어 1분간 말합니다. 그리고 말한 내용을 그대로 적으세요.", checkpoint: '', placeholder: "[1분 버전] 키워드 + 연결문장을 보고 말한 후, 그대로 받아 적으세요", referenceQuestions: ["Q13", "Q14", "Q15", "Q16", "Q17"], relatedWorkbooks: ['self_introduction', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
      { label: "Q20", question: "초안 다듬기", tip: "① 흐름 확인 (첫 문장→경험→깨달음→강점→기여방향 순서가 자연스러운가) · ② 불필요한 문장 삭제 · ③ 시간 측정 (30초/1분 안에 들어오는지)", checkpoint: '', placeholder: "[1분 버전 수정본] 초안을 다듬은 후 여기에 적으세요", referenceQuestions: ["Q19"], relatedWorkbooks: ['experience', 'self_introduction', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
    ],
  },
];

export const CHECKLIST = [
  { label: "Q21", criteria: "직무 이해도", question: "채용담당자가 \"이 사람이 우리 직무의 핵심을 이해하고 있구나\"라고 느끼는가?", fallback: "아니오 → PART 1 다시 보완", relatedWorkbooks: ['job_analysis', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
  { label: "Q22", criteria: "즉시 전력화", question: "채용담당자가 \"이 사람이 입사하면 어떤 업무를 할 수 있겠다\"를 구체적으로 떠올릴 수 있는가?", fallback: "아니오 → PART 2 다시 보완", relatedWorkbooks: ['experience', 'self_introduction', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
  { label: "Q23", criteria: "성과 창출", question: "경험과 성과가 \"이 사람은 실제로 결과를 만들어낼 수 있겠다\"는 인상을 주는가?", fallback: "아니오 → PART 2~3 다시 보완", relatedWorkbooks: ['experience', 'self_introduction', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
  { label: "Q24", criteria: "함께 일하고 싶은 동료", question: "강점이 \"성실함\" 같은 범용 표현이 아니라, 직무에서 구체적으로 어떻게 쓰이는지까지 연결되어 있는가?", fallback: "아니오 → PART 3 다시 보완", relatedWorkbooks: ['experience', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
  { label: "Q25", criteria: "오래 함께할 사람", question: "지원동기와 기여방향이 \"어떤 회사에도 쓸 수 있는 말\"이 아니라, 이 회사에만 해당되는 구체적 내용인가?", fallback: "아니오 → PART 4 다시 보완", relatedWorkbooks: ['experience', 'self_introduction', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
  { label: "Q26", criteria: "전체 흐름", question: "첫 문장부터 마지막까지 자연스럽게 이어지고, 꼬리질문이 나와도 일관성 있게 답할 수 있는가?", fallback: "아니오 → PART 6 다시 보완", relatedWorkbooks: ['interview_new', 'interview_career', 'motivation', 'jobcompetency', 'personality', 'goalachievement', 'careergoal'] },
];
